Fix test_bloom.py fail after tt-forge-models updates (loader.test_input instead of ModelLoader.test_input) (#1008)
### Ticket
None

### Problem description
- Test failed on Nightly with "AttributeError: type object 'ModelLoader'
has no attribute 'test_input'" after tt-forge-models update

### What's changed
- Need to use loader.test_input instead of ModelLoader.test_input

### Checklist
- [x] Passes locally now