Fix OnnxModelTester -> ModelTester init missing new loader arg from prev commit (onnx model fails in nightly) (#995)
### Ticket
None

### Problem description
- The few onnx tests we have are failing with "AttributeError: 'bool'
object has no attribute 'model_name'" or "AssertionError: Exactly one of
required_atol or relative_atol should be provided."
- It's due to change yesterday to add optional "loader" arg to
ModelTester's init function but missed an update.

### What's changed
- Fix missing argument in ModelTester init call from OnnxModelTester init
- And add a 10 second onnx test to onPR/onPush list for coverage, was only caught in nightly

### Checklist
- [x] Tested all onnx tests locally, passing now