Restore back tester.test_input variable in test_yolos*.py for ending summary (#930)
### Ticket
None

### Problem description
- Tiny refactor, removal of this variable caused single device and n300 to fail in nightly
with error "AttributeError: 'ThisTester' object has no attribute 'test_input'"

### What's changed
- Add variable back to avoid error since it is used at end of test

### Checklist
- [x] Checked tests locally