Pin torchcodec to 0.5.0 for Whisper, remove tt-forge-models-tests.yml dummy cron, show python deps in full model tests (#1157)
### Ticket
None

### Problem description
Misc CI fixes from Aug 8

### What's changed
- Torchcodec upgraded to 0.6.0 inducing new failure in test_whisper
NotImplementedError: Could not run 'torchcodec_ns::create_from_tensor'
with arguments from the 'CPU' backend. Pin to 0.5.0
- Remove dummy cron job from tt-forge-models-tests.yml which didn't work
- Add step to show python deps in full model tests

### Checklist
- [x] Quick onPush test to check that full model tests still work

---------

Co-authored-by: Kyle Mabee <kmabee@tenstorrent.com>